---
title: "github-graph"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r imports}

library(igraph)
library(kableExtra)
library(bipartite)
library(networkD3)
library(bipartite)
```

```{r data}


entire_data       <- read.table("compressed_edge.data", sep = "\t", header = FALSE)
data              <- entire_data[c(1:1500),]
graph_data        <- graph.data.frame(data,directed = TRUE)

head(data, 100)
```

``` {r force-interactive}


wc <- cluster_walktrap(graph_data)
members <- membership(wc)
graph_d3 <- igraph_to_networkD3(graph_data, group = members)
graph_d3$links$value = 1
depth_data = aggregate(data$V4, by=list(data$V1), FUN=function(x) x[1])
graph_d3$nodes$depth = 100
graph_d3$nodes[graph_d3$nodes$name %in% depth_data$Group.1,]$depth = (5 - as.numeric(depth_data[match(depth_data$Group.1, graph_d3$nodes$name),]$x)) * 100



p = forceNetwork(
             Links = graph_d3$links,
             Nodes = graph_d3$nodes, 
             charge = -100,
             Source = 'source',
             Target = 'target', 
             NodeID = 'name',
             Group = 'group',
             Value = 'value',
             Nodesize = 'depth',
             zoom = T,
             opacityNoHover = T,
             arrows = T
             )
p
```
``` {r}
graph_d3$nodes
```


``` {r plot}
small_data              <- entire_data[c(1:30),]
small_graph_data        <- graph.data.frame(small_data,directed = TRUE)
g = small_graph_data

plot(g)
```

``` {r bipart_1}
library(tidyr)

entire_lang_data       <- read.table("compressed_lang.data", sep = "\t", header = FALSE)
lang_data              <- entire_lang_data[c(1:12),]
lang_graph_data        <- graph.data.frame(lang_data, directed = F)

V(lang_graph_data)$type <- bipartite_mapping(lang_graph_data)$type

data_attr = as.numeric(unlist(vertex_attr(lang_graph_data), FALSE))
topValue = max(lang_data$V3)
# more red less confidence
E(lang_graph_data)$color <- rgb(topValue - lang_data$V3, 0, 0, maxColorValue = topValue);
tkplot(lang_graph_data)

la = layout.bipartite
plot(lang_graph_data, layout=la)

# count occurrences of languages
table(entire_lang_data$V2)
```

``` {r bipart_2}
library(tidyr)

entire_lang_fix_data       <- read.table("compressed_lang_fix.data", sep = "\t", header = FALSE)
lang_data_fix              <- entire_lang_fix_data[c(1:12),]
lang_graph_fix_data        <- graph.data.frame(lang_data_fix, directed = F)

V(lang_graph_fix_data)$type <- bipartite_mapping(lang_graph_fix_data)$type

data_attr = as.numeric(unlist(vertex_attr(lang_graph_fix_data), FALSE))
topValue = max(lang_data_fix$V3)

# more red less confidence
E(lang_graph_fix_data)$color <- rgb(topValue - lang_data_fix$V3, 0, 0, maxColorValue = topValue);
tkplot(lang_graph_fix_data)

la = layout.bipartite
plot(lang_graph_fix_data, layout=la)

# count occurrences of languages
table(entire_lang_fix_data$V2)
```